### ISSUE TITLE
Investigate - Push subscription has unsubscribed or expired.

### ISSUE THREAD

**Issue by dbrennand** [dbrennand/PS2Alert.me#3]
The logs for the `consumer` contain several errors which I haven't seen before. The errors indicate that push notifications are not being delivered.

```
{"level":"error","time":1634065886760,"msg":"push subscription has unsubscribed or expired.\n"}
{"level":"error","time":1634065886761,"msg":"push subscription has unsubscribed or expired.\n"}
{"level":"error","time":1634065886761,"msg":"push subscription has unsubscribed or expired.\n"}
```

This needs to be investigated further.

Users are *highly likely* to not be receiving push notifications due to this.

Seems to only be occuring for subscriptions that come from Chromium based browsers.

**Comment by dbrennand** [comment]
Pushpad blog with information related to this: https://blog.pushpad.xyz/2021/01/web-push-error-410-the-push-subscription-has-expired-or-the-user-has-unsubscribed/.

**Comment by dbrennand** [comment]
Other useful links:

https://www.w3.org/TR/push-api/#subscription-refreshes

https://blog.pushpad.xyz/2016/05/the-push-api-and-its-wild-unsubscription-mechanism/

https://github.com/w3c/push-api/issues/116

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event

**Comment by dbrennand** [comment]
# Tasks

- [x] Add event listener for `pushsubscriptionchange` in sw.js - Commit: 1169420
- [x] Add new endpoint `/edit-subscription` to backend/index.js - Commit: a81472c
- [x] Investigate how/if CSRF protection can be implemented with service worker when `pushsubscriptionchange` event occurs.
- [x] Test `pushsubscriptionchange` works correctly.

**Comment by dbrennand** [comment]
Work for this is being done in [v2.1 branch](https://github.com/dbrennand/PS2Alert.me/tree/v2.1).

**Comment by dbrennand** [comment]
A good example of a push notification service worker from [PushPad](https://pushpad.xyz/service-worker.js) doesn't seem to implement any CSRF protections when a `pushsubscriptionchange` event occurs.

**Comment by dbrennand** [comment]
Testing `pushsubscriptionchange` is going to be a challenge.

See https://stackoverflow.com/questions/36602136/how-can-i-test-pushsubscriptionchange-event-handling-code and https://bugs.chromium.org/p/chromium/issues/detail?id=753163

**Comment by dbrennand** [comment]
Tested the `/edit-subscription` API route using `curl`. 

Replicated payload that would be sent by the service worker. HTTP 200 OK response 👍🏻 

Unfortunately, I couldn't get Firefox or Chrome to trigger the `pushsubscriptionchange` event when altering the browser permissions 😞

**Comment by dbrennand** [comment]
Deployed to production. Will monitor in the coming days.

**Comment by dbrennand** [comment]
I've been looking a little deeper into the `pushsubscriptionchange` event. Much of the push APIs (`PushEvent, PushManager` etc are experimental and due to their experimental nature, the findings below are not that suprising.

Here is the current (working draft) [W3 specification](https://www.w3.org/TR/push-api/#the-pushsubscriptionchange-event) for the `pushsubscriptionchange` event. 

The specification indicates that the `PushSubscriptionChangeEvent` interface should have two attributes: `newSubscription` and `oldSubscription`. However, conversations in [push-api/issues/325](https://github.com/w3c/push-api/issues/325) show that when `pushsubscriptionchange` fires in Firefox, these two attributes are `undefined` as it has not been implemented yet:

Taken from: https://github.com/w3c/push-api/issues/325#issuecomment-625680151

> [Here's the code inside of Firefox that creates and triggers pushsubscriptionchange](https://searchfox.org/mozilla-central/rev/dc4560dcaafd79375b9411fdbbaaebb0a59a93ac/dom/serviceworkers/ServiceWorkerOp.cpp#755-756,759-760) - you can see it's creating a regular ExtendableEvent instead of a PushSubcriptionChangeEvent that the spec says we should create.

I'm not expert in cpp but it appears to still be that way today:

Commit hash: [9b0bdcc3](https://searchfox.org/mozilla-central/commit/9b0bdcc37419e6765223358a31a4a54d62e1cd97)
File: [`ServiceWorkerOp.cpp`](https://searchfox.org/mozilla-central/source/dom/serviceworkers/ServiceWorkerOp.cpp#754)

This presents an issue for users of Firefox who use PS2Alert.me. When the subscription eventually expires, there is no *quick/easy* way of sending the new subscription data to the server. Luckily, there is a workaround documented [here](https://medium.com/@madridserginho/how-to-handle-webpush-api-pushsubscriptionchange-event-in-modern-browsers-6e47840d756f) that I could try implementing.

Looking to Chrome, the `PushSubscriptionChangeEvent` is [not implemented](https://chromestatus.com/feature/6242325854420992) at the time of writing this comment. Further evidence for this can be found in this [chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1078367#c3). However, for now Chrome seems to be OK for expiring subscriptions as the push provider it uses ([Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/)) does not expire subscriptions:

> It's on our roadmap, but not a major priority for us right now. FCM (our push provider) does not expire subscriptions.

[Peter's final comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1078367#c8) hints that `pushsubscriptionchange` may be coming to Chrome sometime this year:

> We still plan to ship this, but it most likely will be delayed until 2022.

Looking to Microsoft Edge, the [status page](https://developer.microsoft.com/en-us/microsoft-edge/status/pushapi/?q=push) points to the Push API being supported. However, to what extent I'm not sure (e.g. Is `PushSubscriptionChangeEvent` supported).

**Comment by dbrennand** [comment]
The recommended library: https://github.com/RyotaSugawara/serviceworker-storage from the medium post is now readonly.

Looking into using: https://github.com/jakearchibald/idb

EDIT: I only need to `set` and `get` to IndexedDB. Now looking at: https://www.npmjs.com/package/idb-keyval

**Comment by dbrennand** [comment]
Further work is being done in branch [v2.2](https://github.com/dbrennand/PS2Alert.me/tree/v2.2) - Changes to be implemented to production soon.

**Comment by dbrennand** [comment]
Changes implemented into production. To monitor over the coming days again.

**Comment by dbrennand** [comment]
Testing with Firefox, the `pushsubscriptionchange` event fired however, the following error was thrown by the service worker:

![Screenshot 2022-03-06 113638](https://user-images.githubusercontent.com/52419383/156923184-1cf92787-f32b-4d7f-be81-f05b417f3247.png)

![Screenshot 2022-03-06 110452](https://user-images.githubusercontent.com/52419383/156923187-77444b09-4e85-4c8b-b3ac-41e1752abc53.png)

At line [26](https://github.com/dbrennand/PS2Alert.me/blob/v2.2/frontend/sw.js#L26) indicating that `newSubscription` was `null`. Furthermore, this indicates that Firefox does not re-create the subscription when it expires and a new subscription needs to be created manually. 

The service worker will need the Public VAPID key and `urlBase64ToUint8Array` function to do this.

**Comment by dbrennand** [comment]
Changes deployed to production.
